<a href="https://colab.research.google.com/github/deepacoder/weatherapi/blob/main/trialapiweather1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import json
import pandas as pd
from datetime import datetime, timedelta
import re

In [ ]:
API_key = '78370584546bc1f2a8bddee1dd7b0382'

In [ ]:
#city = 'berlin'

#today = str(datetime.now().date() + timedelta(days=1))
#day_after = str(datetime.now().date() + timedelta(days=2))
#url = "http://api.openweathermap.org/data/2.5/forecast?q="+city+"&appid="+API_key+"&units=metric"
#response = requests.request("GET", url)
#weather = response.json()
#weather = pd.json_normalize(weather,'list', [['city', 'name']], errors='ignore') 
#weather['dt_txt'] = pd.to_datetime(weather['dt_txt'])
#weather = weather.loc[(weather['dt_txt'] >= today ) & (weather['dt_txt'] <= day_after)]
#weather

In [ ]:
#weather.columns = (weather.columns.str.strip().str.replace('.', '_'))
#weather.head(2)

In [ ]:
city = 'Berlin'
#def get_weather(city):
today = str(datetime.now().date() + timedelta(days=1))
day_after = str(datetime.now().date() + timedelta(days=2))
url = "http://api.openweathermap.org/data/2.5/forecast?q="+city+"&appid="+API_key+"&units=metric"
response = requests.request("GET", url)
weather = response.json()
weather
df = pd.json_normalize(weather,['list'],[['city', 'name'],['city','country']], errors='ignore')
df1 = pd.json_normalize(data= weather['list'], record_path = ['weather'])
df1
weather_df = pd.concat([df, df1], axis=1)
weather_df.columns = (weather_df.columns.str.strip().str.replace('.', '_'))
weather_df['dt_txt'] = pd.to_datetime(weather_df['dt_txt'])
weather_df = weather_df[['dt_txt', 'pop','main_temp','wind_speed','city_name', 'city_country','main', 'description']]
weather_df = weather_df.loc[(weather_df['dt_txt'] >= today ) & (weather_df['dt_txt'] < day_after)]
weather_df.rename(columns={'dt_txt' : 'time', 'pop':'chance_of_rain','main_temp':'avg_temp', 'wind_speed': 'wind_speed', 'city_name': 'city_name',	'city_country':'country_code',
                    'main': 'cloud_cover', 'description': 'forecast'})
weather_df['ingested_time'] = datetime.now()
#return weather_df

<ipython-input-5-d451a01c9738>:13: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  weather_df.columns = (weather_df.columns.str.strip().str.replace('.', '_'))

In [ ]:
weather_df

,dt_txt,pop,main_temp,wind_speed,city_name,city_country,main,description,ingested_time
3,2023-03-04 00:00:00,0.00,1.57,5.72,Berlin,DE,Clouds,scattered clouds,2023-03-03 13:53:27.501447
4,2023-03-04 03:00:00,0.00,2.50,6.76,Berlin,DE,Clouds,broken clouds,2023-03-03 13:53:27.501447
5,2023-03-04 06:00:00,0.20,3.64,5.63,Berlin,DE,Rain,light rain,2023-03-03 13:53:27.501447
6,2023-03-04 09:00:00,0.00,5.03,6.91,Berlin,DE,Clouds,overcast clouds,2023-03-03 13:53:27.501447
7,2023-03-04 12:00:00,0.00,6.18,6.50,Berlin,DE,Clouds,overcast clouds,2023-03-03 13:53:27.501447
8,2023-03-04 15:00:00,0.01,5.20,4.94,Berlin,DE,Clouds,overcast clouds,2023-03-03 13:53:27.501447
9,2023-03-04 18:00:00,0.00,2.05,2.81,Berlin,DE,Clouds,overcast clouds,2023-03-03 13:53:27.501447
10,2023-03-04 21:00:00,0.01,0.67,1.70,Berlin,DE,Clouds,overcast clouds,2023-03-03 13:53:27.501447

In [ ]:
list_of_cities = ['Berlin', 'Hamburg', 'Munich', 'Frankfurt', 'Dusseldorf', 'Stuttgart', 'Cologne']

In [ ]:
results = []
for city in list_of_cities:
  result = get_weather(city)
  results.append(result)

results

<ipython-input-12-f0ef4c5a8b92>:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  weather_df.columns = (weather_df.columns.str.strip().str.replace('.', '_'))

[               dt_txt  pop  main_temp  wind_speed city_name city_country  \
 1 2023-02-28 00:00:00    0       0.24        1.80    Berlin           DE
 2 2023-02-28 03:00:00    0      -1.01        1.61    Berlin           DE
 3 2023-02-28 06:00:00    0      -1.26        1.66    Berlin           DE
 4 2023-02-28 09:00:00    0       1.88        1.97    Berlin           DE
 5 2023-02-28 12:00:00    0       4.32        2.04    Berlin           DE
 6 2023-02-28 15:00:00    0       4.78        2.14    Berlin           DE
 7 2023-02-28 18:00:00    0       1.60        1.97    Berlin           DE
 8 2023-02-28 21:00:00    0       0.19        1.38    Berlin           DE

      main description              ingested_time
 1   Clear   clear sky 2023-02-27 18:22:02.563957
 2  Clouds  few clouds 2023-02-27 18:22:02.563957
 3   Clear   clear sky 2023-02-27 18:22:02.563957
 4   Clear   clear sky 2023-02-27 18:22:02.563957
 5   Clear   clear sky 2023-02-27 18:22:02.563957
 6   Clear   clear sky 2023-02-27 18:22:02.563957
 7   Clear   clear sky 2023-02-27 18:22:02.563957
 8   Clear   clear sky 2023-02-27 18:22:02.563957  ,
                dt_txt  pop  main_temp  wind_speed city_name city_country  \
 1 2023-02-28 00:00:00    0       0.57        1.28   Hamburg           DE
 2 2023-02-28 03:00:00    0      -1.02        0.60   Hamburg           DE
 3 2023-02-28 06:00:00    0      -1.20        0.90   Hamburg           DE
 4 2023-02-28 09:00:00    0       2.73        1.00   Hamburg           DE
 5 2023-02-28 12:00:00    0       5.66        1.51   Hamburg           DE
 6 2023-02-28 15:00:00    0       5.57        1.21   Hamburg           DE
 7 2023-02-28 18:00:00    0       1.13        0.63   Hamburg           DE
 8 2023-02-28 21:00:00    0       0.15        0.40   Hamburg           DE

      main       description              ingested_time
 1  Clouds     broken clouds 2023-02-27 18:22:03.289146
 2  Clouds     broken clouds 2023-02-27 18:22:03.289146
 3  Clouds     broken clouds 2023-02-27 18:22:03.289146
 4  Clouds  scattered clouds 2023-02-27 18:22:03.289146
 5  Clouds        few clouds 2023-02-27 18:22:03.289146
 6   Clear         clear sky 2023-02-27 18:22:03.289146
 7   Clear         clear sky 2023-02-27 18:22:03.289146
 8   Clear         clear sky 2023-02-27 18:22:03.289146  ,
                dt_txt  pop  main_temp  wind_speed city_name city_country  \
 1 2023-02-28 00:00:00  0.0      -2.66        4.97    Munich           DE
 2 2023-02-28 03:00:00  0.0      -3.97        4.08    Munich           DE
 3 2023-02-28 06:00:00  0.0      -4.42        3.43    Munich           DE
 4 2023-02-28 09:00:00  0.0      -1.01        4.11    Munich           DE
 5 2023-02-28 12:00:00  0.0       2.60        4.53    Munich           DE
 6 2023-02-28 15:00:00  0.0       3.30        4.21    Munich           DE
 7 2023-02-28 18:00:00  0.0      -0.98        2.60    Munich           DE
 8 2023-02-28 21:00:00  0.0      -1.90        4.15    Munich           DE

      main       description              ingested_time
 1  Clouds   overcast clouds 2023-02-27 18:22:03.988962
 2  Clouds     broken clouds 2023-02-27 18:22:03.988962
 3  Clouds     broken clouds 2023-02-27 18:22:03.988962
 4  Clouds   overcast clouds 2023-02-27 18:22:03.988962
 5  Clouds   overcast clouds 2023-02-27 18:22:03.988962
 6  Clouds   overcast clouds 2023-02-27 18:22:03.988962
 7  Clouds   overcast clouds 2023-02-27 18:22:03.988962
 8  Clouds  scattered clouds 2023-02-27 18:22:03.988962  ,
                dt_txt  pop  main_temp  wind_speed          city_name  \
 1 2023-02-28 00:00:00    0       0.43        3.17  Frankfurt am Main
 2 2023-02-28 03:00:00    0      -1.08        3.44  Frankfurt am Main
 3 2023-02-28 06:00:00    0      -1.00        3.90  Frankfurt am Main
 4 2023-02-28 09:00:00    0       2.04        4.95  Frankfurt am Main
 5 2023-02-28 12:00:00    0       5.51        4.90  Frankfurt am Main
 6 2023-02-28 15:00:00    0       6.35        4.47  Frankfurt am Main
 7 2023-02-28 18:00:00    0       2.87        3.80  Frankfurt am Main
 8 2023-02-28 21:00:00    0       0.66        2.97  Frankfurt am Main

   city_country    main    description              ingested_time
 1           DE   Clear      clear sky 2023-02-27 18:22:04.219408
 2           DE   Clear      clear sky 2023-02-27 18:22:04.219408
 3           DE   Clear      clear sky 2023-02-27 18:22:04.219408
 4           DE  Clouds     few clouds 2023-02-27 18:22:04.219408
 5           DE  Clouds     few clouds 2023-02-27 18:22:04.219408
 6           DE  Clouds  broken clouds 2023-02-27 18:22:04.219408
 7           DE  Clouds  broken clouds 2023-02-27 18:22:04.219408
 8           DE  Clouds     few clouds 2023-02-27 18:22:04.219408  ,
                dt_txt  pop  main_temp  wind_speed   city_name city_country  \
 1 2023-02-28 00:00:00    0       1.72        2.51  Düsseldorf           DE
 2 2023-02-28 03:00:00    0       0.12        2.54  Düsseldorf           DE
 3 2023-02-28 06:00:00    0      -0.22        2.58  Düsseldorf           DE
 4 2023-02-28 09:00:00    0       2.61        3.54  Düsseldorf           DE
 5 2023-02-28 12:00:00    0       5.66        4.13  Düsseldorf           DE
 6 2023-02-28 15:00:00    0       6.61        4.48  Düsseldorf           DE
 7 2023-02-28 18:00:00    0       3.86        3.69  Düsseldorf           DE
 8 2023-02-28 21:00:00    0       2.08        2.74  Düsseldorf           DE

     main description              ingested_time
 1  Clear   clear sky 2023-02-27 18:22:05.099860
 2  Clear   clear sky 2023-02-27 18:22:05.099860
 3  Clear   clear sky 2023-02-27 18:22:05.099860
 4  Clear   clear sky 2023-02-27 18:22:05.099860
 5  Clear   clear sky 2023-02-27 18:22:05.099860
 6  Clear   clear sky 2023-02-27 18:22:05.099860
 7  Clear   clear sky 2023-02-27 18:22:05.099860
 8  Clear   clear sky 2023-02-27 18:22:05.099860  ,
                dt_txt  pop  main_temp  wind_speed  city_name city_country  \
 1 2023-02-28 00:00:00    0      -0.22        4.31  Stuttgart           DE
 2 2023-02-28 03:00:00    0      -1.01        4.11  Stuttgart           DE
 3 2023-02-28 06:00:00    0      -1.27        3.99  Stuttgart           DE
 4 2023-02-28 09:00:00    0       1.06        4.42  Stuttgart           DE
 5 2023-02-28 12:00:00    0       4.43        4.16  Stuttgart           DE
 6 2023-02-28 15:00:00    0       5.30        4.38  Stuttgart           DE
 7 2023-02-28 18:00:00    0       2.12        2.07  Stuttgart           DE
 8 2023-02-28 21:00:00    0       0.68        2.63  Stuttgart           DE

      main       description              ingested_time
 1  Clouds  scattered clouds 2023-02-27 18:22:05.606249
 2  Clouds   overcast clouds 2023-02-27 18:22:05.606249
 3  Clouds   overcast clouds 2023-02-27 18:22:05.606249
 4  Clouds     broken clouds 2023-02-27 18:22:05.606249
 5  Clouds   overcast clouds 2023-02-27 18:22:05.606249
 6  Clouds     broken clouds 2023-02-27 18:22:05.606249
 7  Clouds     broken clouds 2023-02-27 18:22:05.606249
 8  Clouds     broken clouds 2023-02-27 18:22:05.606249  ,
                dt_txt  pop  main_temp  wind_speed city_name city_country  \
 1 2023-02-28 00:00:00    0       1.21        2.06   Cologne           DE
 2 2023-02-28 03:00:00    0      -0.46        2.11   Cologne           DE
 3 2023-02-28 06:00:00    0      -0.73        2.25   Cologne           DE
 4 2023-02-28 09:00:00    0       2.30        3.53   Cologne           DE
 5 2023-02-28 12:00:00    0       5.49        3.62   Cologne           DE
 6 2023-02-28 15:00:00    0       6.57        3.89   Cologne           DE
 7 2023-02-28 18:00:00    0       3.24        2.89   Cologne           DE
 8 2023-02-28 21:00:00    0       1.32        2.54   Cologne           DE

      main description              ingested_time
 1  Clouds  few clouds 2023-02-27 18:22:06.477141
 2   Clear   clear sky 2023-02-27 18:22:06.477141
 3   Clear   clear sky 2023-02-27 18:22:06.477141
 4   Clear   clear sky 2023-02-27 18:22:06.477141
 5   Clear   clear sky 2023-02-27 18:22:06.477141
 6   Clear   clear sky 2023-02-27 18:22:06.477141
 7  Clouds  few clouds 2023-02-27 18:22:06.477141
 8   Clear   clear sky 2023-02-27 18:22:06.477141  ]

In [ ]:
weather_df = pd.concat(results)

In [ ]:
weather_df

,dt_txt,pop,main_temp,wind_speed,city_name,city_country,main,description,ingested_time
1,2023-02-28 00:00:00,0.0,0.24,1.80,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
2,2023-02-28 03:00:00,0.0,-1.01,1.61,Berlin,DE,Clouds,few clouds,2023-02-27 18:22:02.563957
3,2023-02-28 06:00:00,0.0,-1.26,1.66,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
4,2023-02-28 09:00:00,0.0,1.88,1.97,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
5,2023-02-28 12:00:00,0.0,4.32,2.04,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
6,2023-02-28 15:00:00,0.0,4.78,2.14,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
7,2023-02-28 18:00:00,0.0,1.60,1.97,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
8,2023-02-28 21:00:00,0.0,0.19,1.38,Berlin,DE,Clear,clear sky,2023-02-27 18:22:02.563957
1,2023-02-28 00:00:00,0.0,0.57,1.28,Hamburg,DE,Clouds,broken clouds,2023-02-27 18:22:03.289146
2,2023-02-28 03:00:00,0.0,-1.02,0.60,Hamburg,DE,Clouds,broken clouds,2023-02-27 18:22:03.289146
3,2023-02-28 06:00:00,0.0,-1.20,0.90,Hamburg,DE,Clouds,broken clouds,2023-02-27 18:22:03.289146
4,2023-02-28 09:00:00,0.0,2.73,1.00,Hamburg,DE,Clouds,scattered clouds,2023-02-27 18:22:03.289146
5,2023-02-28 12:00:00,0.0,5.66,1.51,Hamburg,DE,Clouds,few clouds,2023-02-27 18:22:03.289146
6,2023-02-28 15:00:00,0.0,5.57,1.21,Hamburg,DE,Clear,clear sky,2023-02-27 18:22:03.289146
7,2023-02-28 18:00:00,0.0,1.13,0.63,Hamburg,DE,Clear,clear sky,2023-02-27 18:22:03.289146
8,2023-02-28 21:00:00,0.0,0.15,0.40,Hamburg,DE,Clear,clear sky,2023-02-27 18:22:03.289146
1,2023-02-28 00:00:00,0.0,-2.66,4.97,Munich,DE,Clouds,overcast clouds,2023-02-27 18:22:03.988962
2,2023-02-28 03:00:00,0.0,-3.97,4.08,Munich,DE,Clouds,broken clouds,2023-02-27 18:22:03.988962
3,2023-02-28 06:00:00,0.0,-4.42,3.43,Munich,DE,Clouds,broken clouds,2023-02-27 18:22:03.988962
4,2023-02-28 09:00:00,0.0,-1.01,4.11,Munich,DE,Clouds,overcast clouds,2023-02-27 18:22:03.988962
5,2023-02-28 12:00:00,0.0,2.60,4.53,Munich,DE,Clouds,overcast clouds,2023-02-27 18:22:03.988962
6,2023-02-28 15:00:00,0.0,3.30,4.21,Munich,DE,Clouds,overcast clouds,2023-02-27 18:22:03.988962
7,2023-02-28 18:00:00,0.0,-0.98,2.60,Munich,DE,Clouds,overcast clouds,2023-02-27 18:22:03.988962
8,2023-02-28 21:00:00,0.0,-1.90,4.15,Munich,DE,Clouds,scattered clouds,2023-02-27 18:22:03.988962
1,2023-02-28 00:00:00,0.0,0.43,3.17,Frankfurt am Main,DE,Clear,clear sky,2023-02-27 18:22:04.219408
2,2023-02-28 03:00:00,0.0,-1.08,3.44,Frankfurt am Main,DE,Clear,clear sky,2023-02-27 18:22:04.219408
3,2023-02-28 06:00:00,0.0,-1.00,3.90,Frankfurt am Main,DE,Clear,clear sky,2023-02-27 18:22:04.219408
4,2023-02-28 09:00:00,0.0,2.04,4.95,Frankfurt am Main,DE,Clouds,few clouds,2023-02-27 18:22:04.219408
5,2023-02-28 12:00:00,0.0,5.51,4.90,Frankfurt am Main,DE,Clouds,few clouds,2023-02-27 18:22:04.219408
6,2023-02-28 15:00:00,0.0,6.35,4.47,Frankfurt am Main,DE,Clouds,broken clouds,2023-02-27 18:22:04.219408
7,2023-02-28 18:00:00,0.0,2.87,3.80,Frankfurt am Main,DE,Clouds,broken clouds,2023-02-27 18:22:04.219408
8,2023-02-28 21:00:00,0.0,0.66,2.97,Frankfurt am Main,DE,Clouds,few clouds,2023-02-27 18:22:04.219408
1,2023-02-28 00:00:00,0.0,1.72,2.51,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
2,2023-02-28 03:00:00,0.0,0.12,2.54,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
3,2023-02-28 06:00:00,0.0,-0.22,2.58,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
4,2023-02-28 09:00:00,0.0,2.61,3.54,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
5,2023-02-28 12:00:00,0.0,5.66,4.13,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
6,2023-02-28 15:00:00,0.0,6.61,4.48,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
7,2023-02-28 18:00:00,0.0,3.86,3.69,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
8,2023-02-28 21:00:00,0.0,2.08,2.74,Düsseldorf,DE,Clear,clear sky,2023-02-27 18:22:05.099860
1,2023-02-28 00:00:00,0.0,-0.22,4.31,Stuttgart,DE,Clouds,scattered clouds,2023-02-27 18:22:05.606249
2,2023-02-28 03:00:00,0.0,-1.01,4.11,Stuttgart,DE,Clouds,overcast clouds,2023-02-27 18:22:05.606249
3,2023-02-28 06:00:00,0.0,-1.27,3.99,Stuttgart,DE,Clouds,overcast clouds,2023-02-27 18:22:05.606249
4,2023-02-28 09:00:00,0.0,1.06,4.42,Stuttgart,DE,Clouds,broken clouds,2023-02-27 18:22:05.606249
5,2023-02-28 12:00:00,0.0,4.43,4.16,Stuttgart,DE,Clouds,overcast clouds,2023-02-27 18:22:05.606249
6,2023-02-28 15:00:00,0.0,5.30,4.38,Stuttgart,DE,Clouds,broken clouds,2023-02-27 18:22:05.606249
7,2023-02-28 18:00:00,0.0,2.12,2.07,Stuttgart,DE,Clouds,broken clouds,2023-02-27 18:22:05.606249
8,2023-02-28 21:00:00,0.0,0.68,2.63,Stuttgart,DE,Clouds,broken clouds,2023-02-27 18:22:05.606249
1,2023-02-28 00:00:00,0.0,1.21,2.06,Cologne,DE,Clouds,few clouds,2023-02-27 18:22:06.477141
2,2023-02-28 03:00:00,0.0,-0.46,2.11,Cologne,DE,Clear,clear sky,2023-02-27 18:22:06.477141
3,2023-02-28 06:00:00,0.0,-0.73,2.25,Cologne,DE,Clear,clear sky,2023-02-27 18:22:06.477141
4,2023-02-28 09:00:00,0.0,2.30,3.53,Cologne,DE,Clear,clear sky,2023-02-27 18:22:06.477141
5,2023-02-28 12:00:00,0.0,5.49,3.62,Cologne,DE,Clear,clear sky,2023-02-27 18:22:06.477141
6,2023-02-28 15:00:00,0.0,6.57,3.89,Cologne,DE,Clear,clear sky,2023-02-27 18:22:06.477141
7,2023-02-28 18:00:00,0.0,3.24,2.89,Cologne,DE,Clouds,few clouds,2023-02-27 18:22:06.477141
8,2023-02-28 21:00:00,0.0,1.32,2.54,Cologne,DE,Clear,clear sky,2023-02-27 18:22:06.477141